### ISSUE TITLE
Billing Address when used in Login scope is not working as expected both for popup and redirect.

### ISSUE THREAD

**Issue by ngrices** [amzn/amazon-payments-magento-plugin#173] opened 2015-06-12 00:14 UTC
Need to do a deep dive on the logic around billing address usage when present in the response from GetOrderReferenceDetails. Currently there is a flag 'use_for_shipping' that is causing the address to not be used correctly in the order.
@islandskater43 will add more information

**Comment by islandskater43** [comment] 2015-06-19 18:49
When enabling the billing address functionality, the shipping address selected during checkout is ignored, and the default shipping address for the account is selected.

It seems this might be related to the use_for_shipping flag. On a side note, we committed a change recently that commented out a line in the Checkout Controller file that was changing the use_for_shipping flag for the shipping address when a billing address is populated.

The issue is reproducible by adding the additional billing_address scope to login, and then making two purchases with two different addresses in the same account. The first order should be fine, the second order should go to the default account address, regardless of which address is selected during checkout.

**Comment by jonahellison** [comment] 2015-06-30 00:06
Issue occurs in v1.3.0. Resolved with #121 (shipping address forcibly set).

**Closed by jonahellison** 2015-06-30 00:06 UTC
Labels: bug, Fix now
