### ISSUE TITLE
SUBTOTAL ISSUE STILL IN THERE

### ISSUE THREAD

**Issue by ianbresnan** [amzn/amazon-payments-magento-plugin#290] opened 2016-10-28 04:03 UTC
Everytime user faced to Doubled Amount subtotal even order just single QTY. Please get this fix.

**Comment by islandskater43** [comment] 2016-11-04 08:49
@ianbresnan - we've consistently been unable to reproduce this issue on a clean instance of magento. Perhaps you can share the amazon diagnostic output? Or, you can share any specific add on extensions you are using that might be conflicting?

**Comment by ianbresnan** [comment] 2016-11-04 10:37
@islandskater43 mate... I try the same with Fresh MAGENTO SETUP too. When Add to Cart any product went to AMAZON payout and back to Cart to update something every time this extension Doubled MY CART sub Total.

**Comment by ianbresnan** [comment] 2016-11-04 10:37
@islandskater43 mate... I try the same with Fresh MAGENTO SETUP too. When Add to Cart any product went to AMAZON payout and back to Cart to update something every time this extension Doubled MY CART sub Total.

**Comment by ianbresnan** [comment] 2016-11-04 10:37
@islandskater43 mate... I try the same with Fresh MAGENTO SETUP too. When Add to Cart any product went to AMAZON payout and back to Cart to update something every time this extension Doubled MY CART sub Total.

**Comment by ianbresnan** [comment] 2016-11-04 10:37
@islandskater43 mate... I try the same with Fresh MAGENTO SETUP too. When Add to Cart any product went to AMAZON payout and back to Cart to update something every time this extension Doubled MY CART sub Total.

**Comment by ianbresnan** [comment] 2016-11-04 10:37
@islandskater43 mate... I try the same with Fresh MAGENTO SETUP too. When Add to Cart any product went to AMAZON payout and back to Cart to update something every time this extension Doubled MY CART sub Total.

**Comment by ianbresnan** [comment] 2016-11-04 10:37
@islandskater43 mate... I try the same with Fresh MAGENTO SETUP too. When Add to Cart any product went to AMAZON payout and back to Cart to update something every time this extension Doubled MY CART sub Total.

**Comment by ianbresnan** [comment] 2016-11-04 10:37
@islandskater43 mate... I try the same with Fresh MAGENTO SETUP too. When Add to Cart any product went to AMAZON payout and back to Cart to update something every time this extension Doubled MY CART sub Total.

**Comment by islandskater43** [comment] 2016-11-07 21:00
Can you detail out the steps you take to create a fresh instance? Here are the steps I've followed where I'm unable to replicate:

1. Launch a new Bitnami instance of Magento 1.9 on AWS.
2. Install the Pay with Amazon plugin

**Comment by islandskater43** [comment] 2016-11-15 20:55
@ianbresnan - can you answer the above? If we can find a way to successfully replicate the issue, then we can try to resolve. Thanks!

**Comment by islandskater43** [comment] 2016-11-16 00:18
Closing as duplicate of #155. @ianbresnan - please provide additional details in issue #155.

**Closed by islandskater43** 2016-11-16 00:18 UTC
Labels: duplicate
